Binus.SampleWebAPI.Web/Binus.SampleWebAPI.Web/ViewModels/msBooks/msBookViewModel.cs
using System.Collections.Generic;
using Binus.SampleWebAPI.Model.Backend.msBook;

namespace Binus.SampleWebAPI.Web.ViewModels.msBooks
{
    public class msBookViewModel
    {
        public msBookMSSQLOracle Book { get; set; }
        public List<msBookMSSQLOracle> Books { get; set; }

        public msBookMonggoDB BookMongoDB { get; set; }
        public List<msBookMonggoDB> BooksMongoDB { get; set; }

    }
}

Binus.SampleWebAPI.Web/Binus.SampleWebAPI.Web/Controllers/Backend/msBook/msBookMSSQLController.cs
using System.Web.Mvc;
using Binus.WebAPI.REST;
using Binus.SampleWebAPI.Web.Class;
using Binus.SampleWebAPI.Web.ViewModels.msBooks;
using Binus.SampleWebAPI.Model.Backend.msBook;
using System.Collections.Generic;
using Binus.SampleWebAPI.Model.Base;
using Binus.SampleWebAPI.Model.Backend.User;

namespace Binus.SampleWebAPI.Web.Controllers.Backend.msBook
{
    [App_Start.BasicAuthentication]
    public class msBookMSSQLController : Controller
    {
        public ActionResult Index()
        {
            RESTResult Result = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookMSSQL/Get", REST.Method.POST).Result);
            if(Result.Success)
            {
                msBookViewModel ViewModel = new msBookViewModel();
                ViewModel.Books = Result.Deserialize<List<msBookMSSQLOracle>>();
                return View(ViewModel);
            }
            else
            {
                return View();
            }
           

        }

        public ActionResult Manipulation(msBookViewModel Data)
        {
            msUser CurrentUser = (msUser)Session["ActiveUser"];
            Data.Book.UserIn = CurrentUser.Nama;
            Data.Book.UserUp = CurrentUser.Nama;
            RESTResult ResultItem = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookMSSQL/Manipulation", REST.Method.POST,Data.Book).Result);
            if (ResultItem.Success)
            {
                return Json(new { Result = "Success", URL = "/msBookMSSQL" });
            }
            else
            {
                return Json(new { Result = "Fail", Message = "Error while manipulate data" });
            }


        }

        public ActionResult Edit(msBookMSSQLOracle Data)
        {
            RESTResult Result = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookMSSQL/Get", REST.Method.POST, Data).Result);
            if (Result.Success)
            {
                return Json(Result.Deserialize<List<msBookMSSQLOracle>>());
            }
            else
            {
                return View();
            }


        }

        public ActionResult Delete()
        {
            RESTResult Result = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookMSSQL/Get", REST.Method.POST).Result);
            if (Result.Success)
            {
                msBookViewModel ViewModel = new msBookViewModel();
                ViewModel.Books = Result.Deserialize<List<msBookMSSQLOracle>>();
                return View(ViewModel);
            }
            else
            {
                return View();
            }


        }
    }
}

Binus.SampleWebAPI.Web/Binus.SampleWebAPI.Web/Controllers/Backend/msBook/msBookMongoDBController.cs
using System.Web.Mvc;
using Binus.WebAPI.REST;
using Binus.SampleWebAPI.Web.Class;
using Binus.SampleWebAPI.Web.ViewModels.msBooks;
using System.Collections.Generic;
using Binus.SampleWebAPI.Model.Backend.User;
using Binus.SampleWebAPI.Model.Backend.msBook;

namespace Binus.SampleWebAPI.Web.Controllers.Backend.msBook
{
    [App_Start.BasicAuthentication]
    public class msBookMongoDBController : Controller
    {
        public ActionResult Index()
        {
            RESTResult Result = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookMongoDB/Get", REST.Method.POST).Result);
            if(Result.Success)
            {
                msBookViewModel ViewModel = new msBookViewModel();
                ViewModel.BooksMongoDB = Result.Deserialize<List<msBookMonggoDB>>();
                return View(ViewModel);
            }
            else
            {
                return View();
            }
           

        }

        public ActionResult Manipulation(msBookViewModel Data)
        {
            msUser CurrentUser = (msUser)Session["ActiveUser"];
            Data.BookMongoDB.UserIn = CurrentUser.Nama;
            Data.BookMongoDB.UserUp = CurrentUser.Nama;
            RESTResult ResultItem = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookMongoDB/Manipulation", REST.Method.POST, Data.BookMongoDB).Result);
            if (ResultItem.Success)
            {
                return Json(new { Result = "Success", URL = "/msBookMongoDB" });
            }
            else
            {
                return Json(new { Result = "Fail", Message = "Error while manipulate data" });
            }


        }

        public ActionResult Edit(msBookMonggoDB Data)
        {
            RESTResult Result = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookMongoDB/Get", REST.Method.POST, Data).Result);
            if (Result.Success)
            {
                return Json(Result.Deserialize<List<msBookMonggoDB>>());
            }
            else
            {
                return View();
            }


        }

    }
}

Binus.SampleWebAPI.Web/Binus.SampleWebAPI.Web/Controllers/Backend/msBook/msBookOracleController.cs
using System.Web.Mvc;
using Binus.WebAPI.REST;
using Binus.SampleWebAPI.Web.Class;
using Binus.SampleWebAPI.Web.ViewModels.msBooks;
using Binus.SampleWebAPI.Model.Backend.msBook;
using System.Collections.Generic;
using Binus.SampleWebAPI.Model.Base;
using Binus.SampleWebAPI.Model.Backend.User;

namespace Binus.SampleWebAPI.Web.Controllers.Backend.msBook
{
    public class msBookOracleController : Controller
    {
        [App_Start.BasicAuthentication]
        public ActionResult Index()
        {
            RESTResult Result = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookOracle/Get", REST.Method.POST).Result);
            if(Result.Success)
            {
                msBookViewModel ViewModel = new msBookViewModel();
                ViewModel.Books = Result.Deserialize<List<msBookMSSQLOracle>>();
                return View(ViewModel);
            }
            else
            {
                return View();
            }
           

        }

        public ActionResult Manipulation(msBookViewModel Data)
        {
            msUser CurrentUser = (msUser)Session["ActiveUser"];
            Data.Book.UserIn = CurrentUser.Nama;
            Data.Book.UserUp = CurrentUser.Nama;
            RESTResult ResultItem = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookOracle/Manipulation", REST.Method.POST, Data.Book).Result);
            if (ResultItem.Success)
            {
                return Json(new { Result = "Success", URL = "/msBookOracle" });
            }
            else
            {
                return Json(new { Result = "Fail", Message = "Error while manipulate data" });
            }


        }

        public ActionResult Edit(msBookMSSQLOracle Data)
        {
            RESTResult Result = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookOracle/Get", REST.Method.POST, Data).Result);
            if (Result.Success)
            {
                return Json(Result.Deserialize<List<msBookMSSQLOracle>>());
            }
            else
            {
                return View();
            }


        }

        public ActionResult Delete()
        {
            RESTResult Result = (new REST(Global.WebAPIBaseURL, "/api/Serpong/BookDB/v1/Backend/msBookOracle/Get", REST.Method.POST).Result);
            if (Result.Success)
            {
                msBookViewModel ViewModel = new msBookViewModel();
                ViewModel.Books = Result.Deserialize<List<msBookMSSQLOracle>>();
                return View(ViewModel);
            }
            else
            {
                return View();
            }


        }
    }
}

Binus.SampleWebAPI.Web/Binus.SampleWebAPI.Web/Views/Backend/msBook/msBookOracle/index.cshtml
@model Binus.SampleWebAPI.Web.ViewModels.msBooks.msBookViewModel
@using Binus.SampleWebAPI.Model.Backend.msBook;
@{
    ViewBag.Title = "Oracle Example";
   
   
}

<div class="container">
    <h2>Oracle Server Books List</h2>
    <p>Sample Code how to use Web API and manage Oracle Data from Web API</p>
    <br/>
    <div class="pull-right"><button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal" data-id="" data-type="Add">Add</button> </div>
    <table class="table">
        <thead>
            <tr>
                <th>ISBN</th>
                <th>BookName</th>
                <th>Author</th>
                <th>Publisher</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (msBookMSSQLOracle Item in Model.Books)
            {
                <tr>
                    <td>@Item.ISBN</td>
                    <td>@Item.BookName</td>
                    <td>@Item.Author</td>
                    <td>@Item.Publisher</td>
                    <td><button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal" data-id="@Binus.WebAPI.Cryptography.Crypto.Encrypt(Item.ID.ToString())" data-type="Edit">Edit</button> <button type="button" class="btn btn-danger" onclick="Delete('@Binus.WebAPI.Cryptography.Crypto.Encrypt(Item.ID.ToString())')">Delete</button></td>
                </tr>
            }
          
        </tbody>
    </table>
@using (Ajax.BeginForm("Manipulation", "msBookMSSQL", new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "LoadResult(data)"
}, new { id = "form" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" id="hdID" name="Book.IDEncrypt" value=""/>
    <input type="hidden" id="hdType" name="Book.Stsrc" value="" />
    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modal Header</h4>
                </div>
                <div class="modal-body">
                   <div class="row Data">
                       <div class="col-sm-12">
                         
                              
                           <div class="alert alert-danger alert-dismissable" id="MessageContainer">
                               <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                               <span id="Message"></span>
                           </div>
                               <div class="form-group">
                                   <label for="txtISBN">ISBN:</label>
                                   <input type="text" class="form-control input-lg" required id="txtISBN" name="Book.ISBN">
                               </div>
                               <div class="form-group">
                                   <label for="txtBookName">Book Name:</label>
                                   <input type="text" class="form-control input-lg" required id="txtBookName" name="Book.BookName">
                               </div>
                               <div class="form-group">
                                   <label for="txtAuthor">Author:</label>
                                   <input type="text" class="form-control input-lg" required id="txtAuthor" name="Book.Author">
                               </div>
                               <div class="form-group">
                                   <label for="txtPublisher">Publisher:</label>
                                   <input type="text" class="form-control input-lg" required id="txtPublisher" name="Book.Publisher">
                               </div>
                               
                          
                           </div>
                       </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Submit</button> <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
           
        </div>
    </div> 
    }
</div>
<script src="~/Sources/PageJS/Backend/msBookOracle.js"></script>